export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Dashboard } from './Dashboard'
export { default as NewAnalysis } from './NewAnalysis'
export { default as Result } from './Result'
export { default as History } from './History'
